"""Add job_url to tracked_jobs and harden schemas

Revision ID: 75279c7f2044
Revises: 2645bddd5c91
Create Date: 2026-04-21 17:35:13.254754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75279c7f2044'
down_revision: Union[str, Sequence[str], None] = '2645bddd5c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_jobs', sa.Column('job_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_jobs', 'job_url')
    # ### end Alembic commands ###
