"""add action_code to activity_logs

Revision ID: 9bc0c8732583
Revises: 1a2b3c4d5e6f
Create Date: 2026-04-24 02:44:55.966940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9bc0c8732583'
down_revision: Union[str, Sequence[str], None] = '1a2b3c4d5e6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('action_code', sa.String(length=50), nullable=False))
    op.alter_column('activity_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('learning_roadmaps', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('resume_versions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('resume_versions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('skill_gaps', 'urgency_weight',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('skill_gaps', 'status',
               existing_type=mysql.ENUM('flagged', 'learning', 'acquired'),
               nullable=False)
    op.alter_column('tracked_jobs', 'status',
               existing_type=mysql.ENUM('bookmarked', 'applied', 'interviewing', 'rejected', 'hired'),
               nullable=False)
    op.alter_column('tracked_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'subscription_tier',
               existing_type=mysql.ENUM('free', 'premium_1', 'premium_2'),
               nullable=False)
    op.alter_column('users', 'generations_used',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'generations_limit',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'bonus_quota',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('vault_snapshots', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vault_snapshots', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('users', 'bonus_quota',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'generations_limit',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'generations_used',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('users', 'subscription_tier',
               existing_type=mysql.ENUM('free', 'premium_1', 'premium_2'),
               nullable=True)
    op.alter_column('tracked_jobs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('tracked_jobs', 'status',
               existing_type=mysql.ENUM('bookmarked', 'applied', 'interviewing', 'rejected', 'hired'),
               nullable=True)
    op.alter_column('skill_gaps', 'status',
               existing_type=mysql.ENUM('flagged', 'learning', 'acquired'),
               nullable=True)
    op.alter_column('skill_gaps', 'urgency_weight',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('resume_versions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('resume_versions', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('learning_roadmaps', 'is_completed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('activity_logs', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('activity_logs', 'action_code')
    # ### end Alembic commands ###
